Update media_dev.yml

diff --git a/.github/workflows/media_dev.yml b/.github/workflows/media_dev.yml
--- a/.github/workflows/media_dev.yml
+++ b/.github/workflows/media_dev.yml
@@ -69,49 +69,49 @@ jobs:
              echo ${ITEMS[@]} | jq -s '.' > $DATA_DIR/product_${LOCALE:0:2}.json
            done
 
-      # - name: Download library-dev.zip from Websoft9 artifact
-      #   run: |
-      #     for i in {1..5}; do
-      #       curl -o library-dev.zip https://artifact.websoft9.com/dev/websoft9/plugin/library/library-dev.zip && break || sleep 1
-      #     done
-      #     if [ -f library-dev.zip ]; then
-      #       unzip -o library-dev.zip -d ./library-dev/
-      #     else
-      #       echo "library-dev.zip download failed"
-      #       exit 1
-      #     fi
+      - name: Download library-dev.zip from Websoft9 artifact
+        run: |
+          for i in {1..5}; do
+            curl -o library-dev.zip https://artifact.websoft9.com/dev/websoft9/plugin/library/library-dev.zip && break || sleep 1
+          done
+          if [ -f library-dev.zip ]; then
+            unzip -o library-dev.zip -d ./library-dev/
+          else
+            echo "library-dev.zip download failed"
+            exit 1
+          fi
 
-      # - name: Merge product version data
-      #   run: |
-      #     IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
-      #     for LOCALE in "${LOCALE_ARRAY[@]}"; do
-      #       PRODUCT_FILE="$DATA_DIR/product_${LOCALE:0:2}.json"
-      #       LIBRARY_APPS_DIR="./library-dev/apps"
+      - name: Merge product version data
+        run: |
+          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
+          for LOCALE in "${LOCALE_ARRAY[@]}"; do
+            PRODUCT_FILE="$DATA_DIR/product_${LOCALE:0:2}.json"
+            LIBRARY_APPS_DIR="./library-dev/apps"
 
-      #       if [ -f "$PRODUCT_FILE" ]; then
-      #         for APP_DIR in "$LIBRARY_APPS_DIR"/*; do
-      #           if [ -d "$APP_DIR" ]; then
-      #             APP_NAME=$(basename "$APP_DIR")
-      #             VARIABLES_FILE="$APP_DIR/variables.json"
+            if [ -f "$PRODUCT_FILE" ]; then
+              for APP_DIR in "$LIBRARY_APPS_DIR"/*; do
+                if [ -d "$APP_DIR" ]; then
+                  APP_NAME=$(basename "$APP_DIR")
+                  VARIABLES_FILE="$APP_DIR/variables.json"
 
-      #             if [ -f "$VARIABLES_FILE" ]; then
-      #               EDITIONS=$(jq -c '.edition' "$VARIABLES_FILE")
-      #               jq --argjson editions "$EDITIONS" --arg app_name "$APP_NAME" '
-      #                 map(
-      #                   if .key == $app_name then
-      #                     .distribution = ($editions | map({dist: .dist, version: .version[]}))
-      #                   else
-      #                     .
-      #                   end
-      #                 )
-      #               ' "$PRODUCT_FILE" > "${PRODUCT_FILE}.tmp" && mv "${PRODUCT_FILE}.tmp" "$PRODUCT_FILE"
-      #             fi
-      #           fi
-      #         done
-      #       else
-      #         echo "Product file $PRODUCT_FILE not found."
-      #       fi
-      #     done
+                  if [ -f "$VARIABLES_FILE" ]; then
+                    EDITIONS=$(jq -c '.edition' "$VARIABLES_FILE")
+                    jq --argjson editions "$EDITIONS" --arg app_name "$APP_NAME" '
+                      map(
+                        if .key == $app_name then
+                          .distribution = ($editions | map({dist: .dist, version: .version[]}))
+                        else
+                          .
+                        end
+                      )
+                    ' "$PRODUCT_FILE" > "${PRODUCT_FILE}.tmp" && mv "${PRODUCT_FILE}.tmp" "$PRODUCT_FILE"
+                  fi
+                fi
+              done
+            else
+              echo "Product file $PRODUCT_FILE not found."
+            fi
+          done
 
       - name: Download directory from Cloudflare R2
         env:
