Update media_dev.yml

diff --git a/.github/workflows/media_dev.yml b/.github/workflows/media_dev.yml
--- a/.github/workflows/media_dev.yml
+++ b/.github/workflows/media_dev.yml
@@ -70,16 +70,23 @@ jobs:
            done
 
       - name: Download library-dev.zip from Websoft9 artifact
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_SECRET_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
         run: |
-          for i in {1..5}; do
-            curl -o library-dev.zip https://artifact.websoft9.com/dev/websoft9/plugin/library/library-dev.zip && break || sleep 1
-          done
-          if [ -f library-dev.zip ]; then
-            unzip -o library-dev.zip -d ./library-dev/
-          else
-            echo "library-dev.zip download failed"
-            exit 1
-          fi
+          aws s3 cp s3://artifact/dev/websoft9/plugin/library/library-dev.zip ./
+          unzip -o library-dev.zip -d ./library-dev/
+
+        # run: |
+        #   for i in {1..5}; do
+        #     curl -o library-dev.zip https://artifact.websoft9.com/dev/websoft9/plugin/library/library-dev.zip && break || sleep 1
+        #   done
+        #   if [ -f library-dev.zip ]; then
+        #     unzip -o library-dev.zip -d ./library-dev/
+        #   else
+        #     echo "library-dev.zip download failed"
+        #     exit 1
+        #   fi
     
       - name: Merge product version data
         run: |
@@ -99,7 +106,7 @@ jobs:
                     jq --argjson editions "$EDITIONS" --arg app_name "$APP_NAME" '
                       map(
                         if .key == $app_name then
-                          .distribution = ($editions | map({dist: .key, version: .value}))
+                          .distribution = ($editions | map({key: .dist, value: .version[]}))
                         else
                           .
                         end
